### ISSUE TITLE
Beautify on Save when selected text

### ISSUE THREAD

**Issue by surjithctly** [victorporof/Sublime-HTMLPrettify#234]
I'm having strange issue when saving. If I'm selected some text, The content breaks. Again we have to save after unselect to beautify again.

Here is a gif to show what I mean.

![save-error](https://cloud.githubusercontent.com/assets/1884712/8455195/7c09939c-2020-11e5-931e-6d1ea8488e72.gif)

Please fix this. its really annoying

**Comment by victorporof** [comment]
Pull requests welcome :)

**Comment by surjithctly** [comment]
I wish I could do. But I don't know python :) I'm just a designer.

**Comment by mike652638** [comment]
Hi Surjithctly,

I came here specially to find the same issue put forward.

Yes, it's strange that HTMLPrettify would add break lines to the selected blocks of code, especially when "HTMLPrettify auto run upon CRTL+S saving .html changes".

After trying uninstall/install HTMLPrettify, I believe it's a bug caused by HTMLPrettify.

Anyone else also encounted such problem please ?
Do anyone know how to avoid such bug ?

Regards,
Mike
mike652638@gmail.com

**Comment by mike652638** [comment]
Hi Surjithctly,

Accidently I solved this headache today.

Here is what I did:

1. Open sublime text 3;
2. Preference>>Package Settings>>HTML/CSS/JS Prettify>>Set Plugin Options
3. "format_selection_only": false,    ("true">>"false")
4.  Save this change.
Done !

Hope it can be helpful to anyone who are suffering this headache, too :)
