### ISSUE TITLE
Sublime text pretify not working when "save_to_temp_file_before_prettifying" is false (new default after plugin update)

### ISSUE THREAD

**Issue by sharadkad123** [victorporof/Sublime-HTMLPrettify#380]
Html pretify is not working

**Comment by victorporof** [comment]
Can you provide more information? It's hard to do anything without any details.

Anything in Sublime's console? Any steps to reproduce?

**Comment by victorporof** [comment]
What is your Sublime version? Are you using a .jsbeautifyrc or .editorconfig file?

**Comment by srm985** [comment]
I also am experiencing issues starting today with Prettify working. Specifically, I'm seeing the error "An unhandled error was encountered while prettifying." I'm running Sublime Text 3, build 3126 and seemingly V2.0.5 of Prettify. This is while trying to prettify a JavaScript file. I did also just update Node to V8.1.4 yesterday but I believe I wasn't having issues prettifying after that. I'll attach a file in which I'm experiencing the issue - I had to attach it as a .txt file because .js wasn't a supported extension. 

I did try to track down the issue by deleting chunks of code but it's a seemingly arbitrary issue. I'd delete one chunk of code and the issue would go away. Then I'd replace it and delete another chunk and that also would remedy the issue. This led me to believe it was a character or line count issue. However, I tried to remove some random single lines of code which seemed to remedy the problem again so I circled back to the idea of a limit on instances of a specific character. I couldn't ever track it down so I came here and noticed there was just a release six hours ago.

[emessaging.txt](https://github.com/victorporof/Sublime-HTMLPrettify/files/1148427/emessaging.txt)

**Comment by victorporof** [comment]
Thanks a lot for this! This plugin was recently updates to use the latest version of jsbeautify (among othet things), so this may be the culprit. I'll try out this file and get back to you.

**Comment by victorporof** [comment]
@srm985 If you enable diagnostics in the plugin settings, can you also paste the sublime console output when prettification fails?

**Comment by victorporof** [comment]
In the meantime anyone experiencing this can rollback to version 1.0, which is the old stable release before today.

**Comment by laricoDGT** [comment]
what I need to do? i've :
"an unhandled error was encountered while prettifying."

**Comment by victorporof** [comment]
@laricoDGT If you enable diagnostics if the plugin settings, what output do you see in sublime's console when prettifying?

**Comment by srm985** [comment]
Only console output was:

[WinError 206] The filename or extension is too long

It's odd because I can prettify other JS files in the same directory with file names as longer or longer. I moved it to the root directory and tried again but still no luck.

**Comment by victorporof** [comment]
@srm985 That's odd. I assume the extension is ".js" or something similar?

**Comment by srm985** [comment]
I am wondering if it has to do with the 256 character limit in Windows? For what it's worth, I'm running Windows 10, 64-bit. Perhaps the program is saving temp files with name that are too long? 

And yes, I have two JS files in the same exact directory, one named emessaging.js and the other named mocked-data.js and I have issues only with emessaging.js.

**Comment by victorporof** [comment]
@srm985 Is setting "save_to_temp_file_before_prettifying" to true in the plugin settings doing anything?

**Comment by srm985** [comment]
Just to see what happened, I replaced the contents of the mocked-data file with the contents of the troublesome emessaging file. I was unable to Prettify the mocked-data file which previously was fine. Guess it's not directly a path or filename issue but somehow the contents of the file.

Hmm... I enabled temp file saving and it resolved the issue. Memory allocation issue for large files?

**Comment by victorporof** [comment]
Piping long text into node processes seem to not work on windows. I'm glad this works around the issue for now. Let's make that the default behavior, care to submit a PR?

**Comment by laricoDGT** [comment]
o "save_to_temp_file_before_prettifying" should be true?

**Comment by laricoDGT** [comment]
Yes, now is working, thank lots

**Comment by srm985** [comment]
I modified the Sublime settings file to set the default as true. I looked through the project and it didn't look like I needed to rebuild anything, but if I missed a step then just let me know. I went ahead and submitted the PR.

**Comment by victorporof** [comment]
Fixed in 2.0.6 https://github.com/victorporof/Sublime-HTMLPrettify/releases
