### ISSUE TITLE
"Unsupported file type" with some files (.sh)

### ISSUE THREAD

**Issue by ZaLiTHkA** [victorporof/Sublime-HTMLPrettify#431]
Is it possible to allow the plugin to apply the most basic of formatting options to a file that isn't explicitly supported? Kinda feels like we're missing out on a bit of EditorConfig's power with not being able to use the `[*]` rule block to apply to everything in a folder. O.o

For example, to a `.sh` file, applying only rules such as indentation style, indentation size, line endings, newline at end of file, etc..

**Comment by ZaLiTHkA** [comment]
Uh... Actually, I think I may have found a small bug.

I tried to use the typical trick of switching my indentation style from space to tab (using ST3's bottom status bar), in order to change indentation size from 4 down to 2, before changing indentation style back to space.

Doing this with "save on focus lost" and "auto format on save": I first open the menu and change indentation to tab (file shows modified state), then I open the menu again to change indentation size, but the file saves and my indentation style is back to space (as per my `[*]` block in my `.editorconfig` file rules).

If I comment out the `indentation_style = space` and go through the same process, then this doesn't happen.

---

I'm actually heading out now for a few hours, so I can't dig into this behaviour too much more at the moment.. If need be, I'll do some more debugging this evening and let you know what I find.

**Comment by victorporof** [comment]
To allow multiple file types, see the allowed file types and allowed file extensions fields in the plugin options (not jsbeautifyrc)

**Comment by victorporof** [comment]
https://github.com/victorporof/Sublime-HTMLPrettify/blob/master/README.md#specifying-which-files-are-allowed-to-be-prettified

**Comment by ZaLiTHkA** [comment]
Ah... I see now, must have missed that readme section earlier. Thanks.

I'll double check my configuration just now and see if there was perhaps something else changing the indentation type then.

**Comment by victorporof** [comment]
Closing this for now. Please reopen if there's anything still not working.

**Comment by ZaLiTHkA** [comment]
Will do. Sorry about not getting back to you about this, I've got family visiting from overseas and things are bit crazy my side at the moment. Hopefully things should be back to normal on my side next week.

**Comment by victorporof** [comment]
No worries! Thanks for your ongoing support.

**Comment by nehbit** [comment]
Just posting it here for posterity, if you want to get .vue files to be prettified, as of June 2018 this is the only way to do it — I was trying to find a way to get .vue files to be run through HTMLPrettify, and this saved my bacon. 

My issue was that if you install sublime vue file highlighting, it breaks HTMLPrettify's 'use_editor_syntax' because it's a new syntax that you just added, which HTMLPrettify doesn't know what to do with. (If you leave the .vue file as HTML editor syntax, prettify works fine but then you don't get vue highlighting) What you need is you need to go to plugin options (not prettify preferences! that lost me ten minutes of confusion) and copy over the "global_file_rules" section to your user version of that file, and add 'vue' to "allowed_file_extensions" of html. This will give you formatting *and* highlighting on vue files. 

There is another prettification plugin called Prettier (their .vue support issue [here](https://github.com/victorporof/Sublime-HTMLPrettify/issues/327)), but unfortunately while they support vue, they don't support html fragments inside it, leaving parts of your .vue file unformatted. HTMLPrettify can format HTML, (S)CSS and JS fragments inside a .vue file, which makes it the only fully working .vue formatter currently available.

**Comment by wakouboy** [comment]
Thanks for nehbit!
